#Docker compose version
version: '3.2'
services:
  alumnos-ds:
    container_name: seguimiento-academico-ds
    restart: always
    build: .
    command: python3 source/app.py runserver
    volumes:
      - .:/app
    ports:
      - "5000:5000"
